### ISSUE TITLE
github  不记录 Contributions

### ISSUE THREAD

**Issue by wave-gbt** [network-center/interesting#16]
如果修改了个人信息，github 会不记录提交贡献
需要重新全局设置个人信息
```
git config --global user.email "你的邮件地址"
git config --global user.name "你的Github用户名"
```
很坑，好多commit记录都丢了~

**Comment by imzyf** [comment]
尝试把你提交 commit 的 email 加入 GitHub 中

**Comment by wave-gbt** [comment]
commit 的 email 事实上一直在github中，github 似乎是以最新的 verified email addresses  为准的。
