### ISSUE TITLE
Chrome 插件 - 汇集

### ISSUE THREAD

**Issue by imzyf** [network-center/interesting#4]
### [DHC REST Client](https://chrome.google.com/webstore/detail/dhc-rest-client/aejoelaoggembcahagimdiliamlcdmfm?hl=en-US)
REST & HTTP API developer's pocket knife. Easy to use and configurable. HATEOAS, Hypermedia, Requests History+Repository, and more.
用于测试 http 请求等等

### [Page Ruler](https://chrome.google.com/webstore/detail/page-ruler/jlpkojjdgbllmedoapgfodplfhcbnbpn?hl=en-US)
Draw a ruler to get pixel dimensions and positioning, and measure elements on any web page.
前端尺子

### [Eye Dropper](https://chrome.google.com/webstore/detail/eye-dropper/hmdcmlfkchdmnmnmheododdhjedfccka)
Eye Dropper is open source extension which allows you to pick colors from web pages, color picker and your personal color history.
拾色器，还可以保存颜色记录

### [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?hl=en-US)
Manage and switch between multiple proxies quickly & easily.
代理工具，很方便定义规则。我觉得可以接替 foxyproxy

### [Wappalyzer](https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg?hl=en-US)
Identifies software on the web
分析网站技术栈

### [SimilarWeb](https://chrome.google.com/webstore/detail/similarweb-site-traffic-s/hoklmmgfnpapgjgcpechhaamimifchmp?hl=en-US)
See real in-depth website engagement, traffic sources, and site ranking information with SimilarWeb
分析网站流量

### [Sexy Undo Close Tab](https://chrome.google.com/webstore/detail/sexy-undo-close-tab/bcennaiejdjpomgmmohhpgnjlmpcjmbg?hl=en-US)
Accidentally closed your last tab? Tired of losing tabs in Incognito? Don't worry, everything is possible with this sexy extension!
恢复关闭的页面

### [Evernote Web Clipper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc?hl=en-US)
Use the Evernote extension to save things you see on the web into your Evernote account.
印象笔记 剪藏；用印象笔记肯定是要安装的插件

**Comment by imzyf** [comment]
### [Personal Blocklist (by Google)](https://chrome.google.com/webstore/detail/personal-blocklist-by-goo/nolijncfnkgaikbjbdaogikpmpbdcdef/related)

在 Google 搜索结果了，自定义屏蔽网站

**Comment by wave-gbt** [comment]
### [Chrome 壁纸插件 Momentum](https://github.com/froginwell/chrome_extensions/blob/master/extensions/Momentum_v0.95.0.crx)

如何可以翻墙，可以直接在chrome extension app store 下载

**Comment by wave-gbt** [comment]
### [Chrome 标签页美化 infinity-pro](https://github.com/wave-gbt/Chrome-Extensions/blob/master/infinity-pro.crx)
Chrome 新标签页应用,重绘了几百个图标,支持自定义搜索,集成天气,带有备忘与 Todo,还可以每日更换壁纸

**Comment by imzyf** [comment]
整理到了 readme，发现新的插件插件可以开新的 issues

**Comment by imzyf** [comment]
整理到了 readme，发现新的插件插件可以开新的 issues
